# Create
POST http://127.0.0.1:5000/advert
Content-Type: application/json

{
  "title": "New advert"
}
###

# Get
GET http://127.0.0.1:5000/advert/1/
Content-Type: application/json
###


# Delete
DELETE http://127.0.0.1:5000/advert/1/
Content-Type: application/json